ALTER TABLE PUBLIC.FEATURES ALTER COLUMN TYPE RENAME TO FEATURETYPE;
ALTER TABLE PUBLIC.SKILLS ALTER COLUMN TYPE RENAME TO SKILLTYPE;
ALTER TABLE PUBLIC.SPECIALIZATIONS ALTER COLUMN TYPE RENAME TO SKILLTYPE;