CREATE TABLE charactersmeleeweapons
(
    ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    CHARACTERID INTEGER NOT NULL,
    MELEEWEAPONID INTEGER NOT NULL,
    COUNT INTEGER,

    FOREIGN KEY (CHARACTERID) REFERENCES CHARACTERS (ID),
    FOREIGN KEY (MELEEWEAPONID) REFERENCES MELEEWEAPONS (ID)
);
