CREATE TABLE charactersguns
(
    ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    CHARACTERID INTEGER NOT NULL,
    GUNID INTEGER NOT NULL,
    COUNT INTEGER,

    FOREIGN KEY (CHARACTERID) REFERENCES CHARACTERS (ID),
    FOREIGN KEY (GUNID) REFERENCES GUNS (ID)
);
