ALTER TABLE CHARACTERSADDONS ALTER COLUMN ADDONID RENAME TO ITEMID;
ALTER TABLE CHARACTERSADDONS DROP COLUMN FEATUREID;
ALTER TABLE CHARACTERSADDONS DROP CONSTRAINT CONSTRAINT_7690;
ALTER TABLE CHARACTERSADDONS ADD FOREIGN KEY (ITEMID) REFERENCES ADDONS (ID);

ALTER TABLE CHARACTERSALCHEMIES ALTER COLUMN ALCHEMYID RENAME TO ITEMID;
ALTER TABLE CHARACTERSALCHEMIES DROP CONSTRAINT CONSTRAINT_D474;
ALTER TABLE CHARACTERSALCHEMIES ADD FOREIGN KEY (ITEMID) REFERENCES ALCHEMIES (ID);

ALTER TABLE CHARACTERSCULTURAS ALTER COLUMN CULTURAID RENAME TO ITEMID;
ALTER TABLE CHARACTERSCULTURAS DROP CONSTRAINT CONSTRAINT_70B1;
ALTER TABLE CHARACTERSCULTURAS ADD FOREIGN KEY (ITEMID) REFERENCES CULTURAS (ID);

ALTER TABLE CHARACTERSEQUIPMENTS ALTER COLUMN EQUIPMENTID RENAME TO ITEMID;
ALTER TABLE CHARACTERSEQUIPMENTS DROP CONSTRAINT CONSTRAINT_612D2;
ALTER TABLE CHARACTERSEQUIPMENTS ADD FOREIGN KEY (ITEMID) REFERENCES EQUIPMENTS (ID);

ALTER TABLE CHARACTERSFEATURES ALTER COLUMN FEATUREID RENAME TO ITEMID;
ALTER TABLE CHARACTERSFEATURES DROP CONSTRAINT CONSTRAINT_472B;
ALTER TABLE CHARACTERSFEATURES ADD FOREIGN KEY (ITEMID) REFERENCES FEATURES (ID);

ALTER TABLE CHARACTERSGRENADES ALTER COLUMN GRENADEID RENAME TO ITEMID;
ALTER TABLE CHARACTERSGRENADES DROP CONSTRAINT CONSTRAINT_2AE0;
ALTER TABLE CHARACTERSGRENADES ADD FOREIGN KEY (ITEMID) REFERENCES GRENADES (ID);

ALTER TABLE CHARACTERSGUNS ALTER COLUMN GUNID RENAME TO ITEMID;
ALTER TABLE CHARACTERSGUNS DROP CONSTRAINT CONSTRAINT_9461;
ALTER TABLE CHARACTERSGUNS ADD FOREIGN KEY (ITEMID) REFERENCES GUNS (ID);

ALTER TABLE CHARACTERSLANGUAGES ALTER COLUMN LANGUAGEID RENAME TO ITEMID;
ALTER TABLE CHARACTERSLANGUAGES DROP CONSTRAINT CONSTRAINT_11DC;
ALTER TABLE CHARACTERSLANGUAGES ADD FOREIGN KEY (ITEMID) REFERENCES LANGUAGES (ID);

ALTER TABLE CHARACTERSMELEEWEAPONRANGEDS ALTER COLUMN MELEEWEAPONRANGEDID RENAME TO ITEMID;
ALTER TABLE CHARACTERSMELEEWEAPONRANGEDS DROP CONSTRAINT CONSTRAINT_C6D9;
ALTER TABLE CHARACTERSMELEEWEAPONRANGEDS ADD FOREIGN KEY (ITEMID) REFERENCES MELEEWEAPONRANGEDS (ID);

ALTER TABLE CHARACTERSMELEEWEAPONS ALTER COLUMN MELEEWEAPONID RENAME TO ITEMID;
ALTER TABLE CHARACTERSMELEEWEAPONS DROP CONSTRAINT CONSTRAINT_C16E;
ALTER TABLE CHARACTERSMELEEWEAPONS ADD FOREIGN KEY (ITEMID) REFERENCES MELEEWEAPONS (ID);

ALTER TABLE CHARACTERSQUIRKS ALTER COLUMN QUIRKID RENAME TO ITEMID;
ALTER TABLE CHARACTERSQUIRKS DROP CONSTRAINT CONSTRAINT_AF0;
ALTER TABLE CHARACTERSQUIRKS ADD FOREIGN KEY (ITEMID) REFERENCES QUIRKS (ID);

ALTER TABLE CHARACTERSSKILLS ALTER COLUMN SKILLID RENAME TO ITEMID;
ALTER TABLE CHARACTERSSKILLS ADD FOREIGN KEY (CHARACTERID) REFERENCES CHARACTERS (ID);
ALTER TABLE CHARACTERSSKILLS ADD FOREIGN KEY (ITEMID) REFERENCES SKILLS (ID);

ALTER TABLE CHARACTERSSPECIALIZATIONS ALTER COLUMN SPECIALIZATIONID RENAME TO ITEMID;
ALTER TABLE CHARACTERSSPECIALIZATIONS ADD FOREIGN KEY (CHARACTERID) REFERENCES SPECIALIZATIONS (ID);
ALTER TABLE CHARACTERSSPECIALIZATIONS ADD FOREIGN KEY (ITEMID) REFERENCES SPECIALIZATIONS (ID);

ALTER TABLE CHARACTERSSPELLS ALTER COLUMN SPELLID RENAME TO ITEMID;
ALTER TABLE CHARACTERSSPELLS ADD FOREIGN KEY (ITEMID) REFERENCES SPELLS (ID);

ALTER TABLE CHARACTERSTECHNIQUES ALTER COLUMN TECHNIQUEID RENAME TO ITEMID;
ALTER TABLE CHARACTERSTECHNIQUES ADD FOREIGN KEY (CHARACTERID) REFERENCES TECHNIQUES (ID);
ALTER TABLE CHARACTERSTECHNIQUES ADD FOREIGN KEY (ITEMID) REFERENCES TECHNIQUES (ID);
