CREATE TABLE ALCHEMIES
(
    ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    NAMEEN VARCHAR(255) NOT NULL,
    ALTERNATIVENAMES VARCHAR(255),
    DESCRIPTION CLOB,
    DURATION VARCHAR(255),
    FORM VARCHAR(255),
    COST VARCHAR(255),
    RECIPE VARCHAR(255) NOT NULL
);
ALTER TABLE ALCHEMIES ADD CONSTRAINT unique_ID UNIQUE (ID);