CREATE TABLE CHARACTERSALCHEMIES
(
    ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    CHARACTERID INTEGER NOT NULL,
    ALCHEMYID INTEGER NOT NULL,
    FOREIGN KEY (CHARACTERID) REFERENCES CHARACTERS (ID),
    FOREIGN KEY (ALCHEMYID) REFERENCES ALCHEMIES (ID)
);
